[project]
name = "🌳"
version = "0.0.1"
description = "Rowan API sample environment"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]
requires-pixi = ">=0.44.0"

[dependencies]
python = ">=3.12"
ruff = ">=0.5"
mypy = ">=1.10"

[pypi-dependencies]
rowan-python ="*"
stjames = "*"

[environments]
default = { solve-group = "default" }

[tasks]
fmt = { cmd="ruff format ." }
lint = { cmd="ruff check . --fix" }
types = { cmd="mypy ." }
all = { depends-on = ["fmt", "lint", "types"] }

[tool.ruff.lint]
select = [
    "B",  # bugbear
    "D",  # pydocstyle
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I",  # isort
    "N",  # pep8-naming conventions
    "W",  # pycodestyle warnings
    "C4", # comprehensions
    "PL", # pylint
    "RUF", # Ruff-specific rules
    "RSE", # flake8-raise
    "ICN001", # unconventional-import-alias
]
ignore = [
    "D100",  # Undocumented public module
    "D101",  # Undocumented public class
    "D102",  # Undocumented public method
    "D103",  # Undocumented public function
    "D104",  # Undocumented public package
    "D105",  # Undocumented magic method
    "E741",  # Ambiguous variable name
    "N801",  # Invalid class name
    "N802",  # Invalid function name
    "N803",  # Invalid argument name
    "N806", # Non-lowercase variable in function
    "N816", # Non-lowercase global variables
    "PLR2004", # Magic value used in comparison
    "PLR0911", # Too many returns
    "PLR0912", # Too many branches
    "PLR0913", # Too many arguments to function call
    "PLR0914", # Too many locals
    "PLR0915", # Too many statements
    "PLR1702", # Too many nested-blocks
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F403"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.mypy]
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = "rdkit-stubs.*"
ignore_errors = true
